<?
    require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
    $APPLICATION->SetTitle("Бриф");
    $APPLICATION->SetPageProperty("page_title_top", "Бриф");
    //$APPLICATION->SetPageProperty("page_title", "Бриф");
?><?$APPLICATION->IncludeComponent(
	"bitrix:iblock.element.add.form", 
	"brief", 
	array(
		"COMPONENT_TEMPLATE" => "brief",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_NAME" => "Как в вам обращаться?",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "",
		"CUSTOM_TITLE_TAGS" => "",
		"DEFAULT_INPUT_SIZE" => "30",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "N",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"GROUPS" => array(
		),
		"IBLOCK_ID" => "12",
		"IBLOCK_TYPE" => "gkexchange",
		"LEVEL_LAST" => "Y",
		"LIST_URL" => "",
		"MAX_FILE_SIZE" => "0",
		"MAX_LEVELS" => "100000",
		"MAX_USER_ENTRIES" => "100000",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
		"PROPERTY_CODES" => array(
			0 => "18",
			1 => "19",
			2 => "20",
			3 => "21",
			4 => "22",
			5 => "23",
			6 => "24",
			7 => "25",
			8 => "26",
			9 => "27",
			10 => "28",
			11 => "29",
			12 => "30",
			13 => "31",
			14 => "32",
			15 => "33",
			16 => "34",
			17 => "35",
			18 => "36",
			19 => "37",
			20 => "38",
			21 => "39",
			22 => "40",
			23 => "41",
			24 => "42",
			25 => "43",
			26 => "44",
			27 => "45",
			28 => "46",
			29 => "47",
			30 => "48",
			31 => "49",
			32 => "50",
			33 => "52",
			34 => "53",
			35 => "54",
			36 => "55",
			37 => "NAME",
		),
		"PROPERTY_CODES_REQUIRED" => array(
			0 => "52",
			1 => "53",
			2 => "54",
			3 => "55",
			4 => "NAME",
		),
		"RESIZE_IMAGES" => "N",
		"SEF_MODE" => "N",
		"STATUS" => "ANY",
		"STATUS_NEW" => "N",
		"USER_MESSAGE_ADD" => "",
		"USER_MESSAGE_EDIT" => "",
		"USE_CAPTCHA" => "N"
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>